# Generated by Django 4.2.18 on 2025-02-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
