# Generated by Django 4.2.18 on 2025-01-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0002_post_status_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
