# Generated by Django 4.2.18 on 2025-01-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='address',
            new_name='content',
        ),
    ]
