# Generated by Django 4.2.18 on 2025-01-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0004_alter_comment_options_rename_body_comment_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Describe the dish or recipe here.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact number (Optional)', max_length=15, null=True),
        ),
    ]
