# Generated by Django 4.2.18 on 2025-02-01 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodhub', '0004_chef_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish_Receipe',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=100,
                     unique=True)),
                ('description',
                 models.TextField(
                     default='No description provided',
                     help_text='Short description of dish')),
                ('small_image',
                 models.ImageField(
                     blank=True,
                     null=True,
                     upload_to='dish_images/')),
                ('big_image',
                 models.ImageField(
                     blank=True,
                     null=True,
                     upload_to='dish_images/')),
                ('chef',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        )]
