# Generated by Django 4.2.18 on 2025-02-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0006_remove_recipe_dish_alter_dish_receipe_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=100)),
                ('description',
                 models.TextField()),
                ('image',
                 models.ImageField(
                     upload_to='menu_images/')),
                ('category',
                 models.CharField(
                     choices=[
                         ('snacks',
                          'Snacks'),
                         ('breakfast',
                          'Breakfast'),
                         ('lunch',
                          'Lunch'),
                         ('dinner',
                          'Dinner')],
                     max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='dish_receipe',
            name='description',
            field=models.TextField(
                help_text='Short description of dish'),
        ),
    ]
