# Generated by Django 4.2.18 on 2025-02-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0007_menuitem_alter_dish_receipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
