# Generated by Django 4.2.18 on 2025-02-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhub', '0011_alter_chef_comment_post_alter_chef_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef_comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
